name: todo_appwrite
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^0.6.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+3
  flutter_screenutil: ^5.0.0+2
  routemaster: ^0.9.0-dev2
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:


  uses-material-design: true
  assets:
    - assets/logos/
  